stages:
  data_ingestion:
    cmd: python -m src.loan_default_prediction.pipeline.stage_01_data_ingestion
    deps:
      - src/loan_default_prediction/pipeline/stage_01_data_ingestion.py
      - src/loan_default_prediction/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Loan_default.csv

  data_validation:
    cmd: python -m src.loan_default_prediction.pipeline.stage_02_data_validation
    deps:
      - src/loan_default_prediction/pipeline/stage_02_data_validation.py
      - src/loan_default_prediction/components/data_validation.py
      - artifacts/data_ingestion/Loan_default.csv
      - config/config.yaml
    outs:
      - artifacts/data_validation/status.txt

  data_preprocessing:
    cmd: python -m src.loan_default_prediction.pipeline.stage_03_data_preprocessing
    deps:
      - src/loan_default_prediction/pipeline/stage_03_data_preprocessing.py
      - src/loan_default_prediction/components/data_preprocessing.py
      - artifacts/data_ingestion/Loan_default.csv
      - config/config.yaml
    outs:
      - artifacts/data_preprocessing/processed_data.csv

  data_transformation:
    cmd: python -m src.loan_default_prediction.pipeline.stage_04_data_transformation
    deps:
      - src/loan_default_prediction/pipeline/stage_04_data_transformation.py
      - src/loan_default_prediction/components/data_transformation.py
      - artifacts/data_preprocessing/processed_data.csv
      - config/config.yaml
    outs:
      - artifacts/data_transformation/split_data/train.csv
      - artifacts/data_transformation/split_data/validation.csv
      - artifacts/data_transformation/split_data/test.csv

  model_training:
    cmd: python -m src.loan_default_prediction.pipeline.stage_05_model_training
    deps:
      - src/loan_default_prediction/pipeline/stage_05_model_training.py
      - src/loan_default_prediction/components/model_training.py
      - artifacts/data_transformation/split_data/train.csv
      - artifacts/data_transformation/split_data/validation.csv
      - artifacts/data_transformation/split_data/test.csv
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/model_training/xgboost_model.pkl
      - artifacts/model_training/model_metrics.json

  model_evaluation:
    cmd: python -m src.loan_default_prediction.pipeline.stage_06_model_evaluation
    deps:
      - src/loan_default_prediction/pipeline/stage_06_model_evaluation.py
      - src/loan_default_prediction/components/model_evaluation.py
      - artifacts/model_training/xgboost_model.pkl
      - artifacts/data_transformation/split_data/test.csv
      - config/config.yaml
      - params.yaml
    outs:
      - artifacts/model_evaluation/model_evaluation_metrics.json

  model_promotion:
    cmd: python -m src.loan_default_prediction.pipeline.stage_07_model_promotion
    deps:
      - src/loan_default_prediction/pipeline/stage_07_model_promotion.py
      - src/loan_default_prediction/components/model_promotion.py
      - artifacts/model_evaluation/model_evaluation_metrics.json
      - artifacts/model_training/xgboost_model.pkl
      - config/config.yaml
    outs:
      - artifacts/model_promotion/promotion_summary.json
      - artifacts/model_promotion/production_model.pkl

  model_inference:
    cmd: python -m src.loan_default_prediction.pipeline.stage_08_inference
    deps:
      - src/loan_default_prediction/pipeline/stage_08_inference.py
      - src/loan_default_prediction/components/inference.py
      - artifacts/model_training/xgboost_model.pkl
      - artifacts/data_transformation/split_data/test.csv
      - config/config.yaml
    outs:
      - artifacts/inference/predictions.csv
